-- 创建 TR 年度三包台账表（费用/结案分析用）
create table if not exists mese_ledger (
  id bigint generated by default as identity primary key,
  serial_number text not null,        -- 三包流水号
  report_year int not null,           -- 年度（如 2025）
  department text,                    -- 提出部门/分公司
  customer_name text,                 -- 客户名称
  warranty_type text,                 -- 三包类型
  material_name text,                 -- 物料名称/描述
  quantity int,                       -- 数量
  amount numeric,                     -- 金额（元）
  resolution text,                    -- 处理方式（维修/换货/返厂等）
  status text,                        -- 结案状态（已结案/未结案等）
  category text,                      -- 问题类别
  cause text,                         -- 原因分类
  apply_date timestamptz,             -- 申请/发生/上报日期
  created_at timestamptz default now()
);

-- 复合唯一键：同一年份下流水号唯一，用于前端 upsert
create unique index if not exists idx_mese_ledger_unique
on mese_ledger (serial_number, report_year);

-- 常用索引
create index if not exists idx_mese_ledger_year on mese_ledger(report_year);
create index if not exists idx_mese_ledger_department on mese_ledger(department);
create index if not exists idx_mese_ledger_category on mese_ledger(category);
create index if not exists idx_mese_ledger_customer on mese_ledger(customer_name);

-- 启用 RLS（与现有表保持一致的开发策略）
alter table mese_ledger enable row level security;
create policy "Allow all access to mese_ledger"
on mese_ledger for all
using (true)
with check (true);

