-- 创建月度周期统计表
create table if not exists mese_cycle_stats (
  id bigint generated by default as identity primary key,
  serial_number text not null, -- 三包流水号
  
  -- 各阶段耗时 (单位: 天)
  hq_dispatch_time numeric, -- 总部制造发运时间
  hq_audit_time numeric, -- 总部审核处置时间
  branch_submit_time numeric, -- 分公司审核提交时间
  supp_invest_time numeric, -- 补充调查时间
  branch_invest_time numeric, -- 分公司现场调查时间
  ship_time numeric, -- 发运时间
  total_cycle_time numeric, -- 全周期统计时间
  
  -- 维度信息
  department text, -- 提出部门
  customer_name text, -- 客户名称
  material_type text, -- 基板/非基板 (从 CSV 最后一列推断，或需额外字段)
  
  -- 统计月份 (例如 '2025-11')
  stat_month text,
  
  created_at timestamptz default now()
);

-- 建立唯一约束 (流水号 + 统计月份)，方便 Upsert
create unique index if not exists idx_mese_cycle_stats_unique 
on mese_cycle_stats (serial_number, stat_month);

-- 启用 RLS
alter table mese_cycle_stats enable row level security;

-- 允许所有读写 (开发环境)
create policy "Allow all access to mese_cycle_stats"
on mese_cycle_stats for all
using (true)
with check (true);
