-- 1. 解除外键约束 (因为 mese_overview 的 serial_number 不再唯一)
alter table mese_person_node drop constraint if exists mese_person_node_serial_number_fkey;

-- 2. 重构 mese_overview 表
-- 先清空旧数据 (因为旧数据被错误地按 serial_number 去重了)
truncate table mese_overview cascade;

-- 修改主键：从 serial_number 变为自增 ID
alter table mese_overview drop constraint if exists mese_overview_pkey;
alter table mese_overview add column if not exists id bigint generated by default as identity primary key;

-- 3. 创建复合唯一索引 (用于 upsert 去重)
-- 使用 serial_number + material_name + drawing_number + warranty_type + fault_description 作为唯一标识
-- 注意：前端需确保这些字段不为 NULL (空值存为空字符串)，否则唯一索引可能失效 (视 PG 版本而定)
drop index if exists idx_mese_overview_unique;
create unique index idx_mese_overview_unique 
on mese_overview (serial_number, department, material_name, drawing_number, warranty_type, fault_description);

-- 4. 确保 mese_person_node 的去重索引存在 (之前已创建，此处防遗漏)
create unique index if not exists idx_mese_person_node_unique 
on mese_person_node (serial_number, start_time, end_time, node, person_name);
